openapi: 3.0.3
info:
  title: Chat App API
  version: 1.0.0
  description: Detailed API documentation for the Chat App
paths:
  /api/login/:
    post:
      operationId: login_create
      tags:
      - login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/messages/:
    get:
      operationId: messages_list
      tags:
      - messages
      parameters:
      - name: user_id
        in: query
        description: ID of the user to fetch messages with
        required: true
        schema:
          type: integer
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
          description: ''
    post:
      operationId: messages_create
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: 'Message created and sent via MQTT'
  /api/messages/{id}/delete/:
    delete:
      operationId: messages_delete_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/messages/{id}/read/:
    put:
      operationId: messages_read_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
    patch:
      operationId: messages_read_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/:
    get:
      operationId: users_list
      tags:
      - users
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserList'
          description: ''
  /api/mqtt-service/:
    post:
      operationId: mqtt_service_create
      summary: "MQTT SERVICE: Test real-time messaging"
      description: "Triggers a real-time MQTT notification. Requires authentication to show your actual sender_id."
      tags:
      - "Real-time Service"
      security:
      - tokenAuth: []
      - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                receiver_id:
                  type: integer
                  description: "ID of the user who will receive the message"
                content:
                  type: string
                  description: "Text content of the notification"
              required:
              - receiver_id
              - content
        required: true
      responses:
        '200':
          description: "MQTT details and payload format"
          content:
            application/json:
              schema:
                type: object
                properties:
                  info: {type: string}
                  mqtt_service_details:
                    type: object
                    properties:
                      topic: {type: string}
                      payload_format: {type: string}
                      exact_payload_sent: {type: object}
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sender:
          type: integer
          readOnly: true
        receiver:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
          readOnly: true
        is_delivered:
          type: boolean
          readOnly: true
        is_read:
          type: boolean
          readOnly: true
      required:
      - content
      - id
      - is_delivered
      - is_read
      - receiver
      - sender
      - timestamp
    PatchedMessage:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sender:
          type: integer
          readOnly: true
        receiver:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
          readOnly: true
        is_delivered:
          type: boolean
          readOnly: true
        is_read:
          type: boolean
          readOnly: true
    Profile:
      type: object
      properties:
        profile_pic:
          type: string
          format: uri
          nullable: true
        is_online:
          type: boolean
        last_seen:
          type: string
          format: date-time
          nullable: true
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - password
      - username
    UserList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        profile:
          allOf:
          - $ref: '#/components/schemas/Profile'
          readOnly: true
        last_message:
          type: string
          readOnly: true
        unread_count:
          type: string
          readOnly: true
      required:
      - id
      - last_message
      - profile
      - unread_count
      - username
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
