openapi: 3.0.3
info:
  title: Chat App API
  version: 1.0.0
  description: Detailed API documentation for the Chat App
paths:
  /api/login/:
    post:
      operationId: login_create
      tags:
      - login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/messages/:
    get:
      operationId: messages_list
      tags:
      - messages
      parameters:
      - name: user_id
        in: query
        description: ID of the user to fetch messages with
        required: true
        schema:
          type: integer
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
          description: ''
    post:
      operationId: messages_create
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
      callbacks:
        new_message_notification:
          'mqtt://broker.hivemq.com/chat/user/{receiver_id}':
            post:
              summary: Real-time notification sent to receiver
              description: Sent via MQTT when a new message is created
              parameters:
              - name: receiver_id
                in: path
                required: true
                schema:
                  type: integer
              requestBody:
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        type: {type: string, example: "new_message"}
                        id: {type: integer, example: 123}
                        sender_id: {type: integer, example: 1}
                        sender: {type: string, example: "john_doe"}
                        content: {type: string, example: "Hello!"}
                        timestamp: {type: string, format: date-time}
  /api/messages/{id}/delete/:
    delete:
      operationId: messages_delete_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
      callbacks:
        message_deleted_notification:
          'mqtt://broker.hivemq.com/chat/user/{receiver_id}':
            post:
              summary: Notification sent to receiver when a message is deleted
              parameters:
              - name: receiver_id
                in: path
                required: true
                schema:
                  type: integer
              requestBody:
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        type: {type: string, example: "message_deleted"}
                        message_id: {type: integer, example: 123}
  /api/messages/{id}/read/:
    put:
      operationId: messages_read_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
      callbacks:
        message_read_notification:
          'mqtt://broker.hivemq.com/chat/user/{sender_id}':
            post:
              summary: Notification sent to sender when their message is read
              parameters:
              - name: sender_id
                in: path
                required: true
                schema:
                  type: integer
              requestBody:
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        type: {type: string, example: "message_read"}
                        message_id: {type: integer, example: 123}
    patch:
      operationId: messages_read_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - messages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMessage'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/:
    get:
      operationId: users_list
      tags:
      - users
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserList'
          description: ''
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sender:
          type: integer
          readOnly: true
        receiver:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
          readOnly: true
        is_delivered:
          type: boolean
          readOnly: true
        is_read:
          type: boolean
          readOnly: true
      required:
      - content
      - id
      - is_delivered
      - is_read
      - receiver
      - sender
      - timestamp
    PatchedMessage:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sender:
          type: integer
          readOnly: true
        receiver:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
          readOnly: true
        is_delivered:
          type: boolean
          readOnly: true
        is_read:
          type: boolean
          readOnly: true
    Profile:
      type: object
      properties:
        profile_pic:
          type: string
          format: uri
          nullable: true
        is_online:
          type: boolean
        last_seen:
          type: string
          format: date-time
          nullable: true
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - password
      - username
    UserList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        profile:
          allOf:
          - $ref: '#/components/schemas/Profile'
          readOnly: true
        last_message:
          type: string
          readOnly: true
        unread_count:
          type: string
          readOnly: true
      required:
      - id
      - last_message
      - profile
      - unread_count
      - username
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
